unit-tests-SkeletonClasses
Sarah-Elhelw/teach_spreadsheets pull request #1
Opened 2020-04-05 11:54 UTC by EpicM

2020-04-07 10:45 UTC, oliviercailloux requested changes
PR depuis votre branche SVP (pour la prochaine fois).

2020-04-07 10:45 UTC, oliviercailloux commented on .gitignore
> +bin/
Ceci ne devrait pas être utile : personne j’imagine n’a besoin de ce répertoire bin localement, qu’il faudrait ignorer.

2020-04-07 10:45 UTC, oliviercailloux commented on pom.xml
> +			<scope>compile</scope>
Pourquoi changez-vous ceci ?

2020-04-07 10:45 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/Course.java
> +    		}
Utilisez plutôt checkNotNull de Guava pour plus de concision. (Voir mes Best practices Null.)

2020-04-07 10:45 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/Course.java
> +    		}
Plutôt checkArgument (et votre test est incorrect, ce qui illustre aussi l’intérêt de checkArgument).

2020-04-07 10:45 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/Course.java
> +		studyYear = "";
Veuillez initialiser explicitement au moins le semestre, et mettre un commentaire ici concernant l’initialisation du reste (normalement tous les champs devraient être initialisés explicitement, dans votre cas comme il y en a beaucoup on peut imaginer laisser l’initialisation à zéro par défaut pour les champs count* et nbHours*).

2020-04-07 10:45 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/Course.java
> +public class Course {
Il est actuellement possible de construire un cours sans lui avoir donné un nom, une année, un semestre, ou aucune heure de cours. Ceci (ou autres configurations impossibles) devrait être interdit !

2020-04-07 10:45 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/Teacher.java
> +public class Teacher {
Même remarque que pour Course : un teacher ne devrait pas exister sans un minimum d’informations vitales (lastName, disons).

2020-04-07 10:45 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/Course.java
> +            courseToBuild = new Course();
Je ne trouve pas cette logique intuitive. Je laisserais le builder dans l’état où il était avant construction, plutôt que le réinitialiser sans rien demander. (Même chose pour Teacher builder). Ainsi, on peut initialiser un cours avec un nom et un semestre, et puis continuer avec le même builder pour un autre cours. Prévoir aussi une méthode pour réinitialiser tous les cours* et hours* à zéro d’un coup.

2020-04-07 10:45 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/Course.java
> +public class Course {
Ajouter une static method factory pour obtenir un Builder, dans Course, et rendre privé le constructeur de Builder. (Même chose pour Teacher.)

2020-04-07 10:45 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/CoursePref.java
> +	 * Degree of preference of teacher for course, represented by chars
Inélégant : seuls A, B, C ou ' ' sont permis et on ne s’en rend pas compte facilement, et on ne comprend pas nécessairement ce que ' ' veut dire. Créer un enum avec ces trois possibilités plus UNSPECIFIED et utiliser ce type pour les prefs.

2020-04-07 10:45 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/CoursePref.java
> +public class CoursePref {
Même remarque que pour Course et Teacher : il devrait être interdit de créer un CoursePref sans un minimum d’informations telles que le nom du cours et de l’enseignant.

En outre, il faut s’assurer que les informations sont cohérentes : une préférence associée à un cours qui n’a pas de TD doit avoir prefTD = UNSPECIFIED, par exemple. (Pour ce faire vous pourriez obliger de spécifier d’entrée un cours et un teacher pour créer un builder, puis vérifier la cohérence au fur et à mesure.)

2020-04-07 10:45 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/CalcData.java
> +public class CalcData {
Indiquer `Immutable` dans la doc (aussi pour Course et autres).

2020-04-07 10:45 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/CalcData.java
> +	private ArrayList<CoursePref> coursePrefs;
`ImmutableSet`

2020-04-07 10:45 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/CalcData.java
> +public class CalcData {
Les en-têtes des méthodes proposées ne sont pas corrects, pour la plupart, et donc devront être changées pour la version CSV et pour la version Json. Mieux vaut effacer la plupart de ces méthodes et attendre de savoir comment on veut les faire. Laissez uniquement une de ces méthodes.

Static method factory permettant d’obtenir un CalcData à partir d’un Teacher et un ensemble de préférences, cela sera au moins utile pour les tests.

2020-04-07 10:45 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/CalcData.java
> +	public static CalcData populateDataFromJSON(String data) {
Celle-ci peut être conservée, si c’est la première que vous comptez implémenter. `fromJson` serait plus approprié.

2020-04-07 10:45 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/CalcData.java
> +}
Il serait gentil de permettre à l’utilisateur de récupérer le `CoursePref` correspondant au cours d’un nom donné: `getCoursePref(String courseName)`. (Au passage, s’assurer également que un seul course pref max existe pour un cours d’un nom donné, au moment de la construction.)

2020-04-07 11:05 UTC, EpicM commented on pom.xml
> +			<scope>compile</scope>
Avec l'ancien scope l'import de la librairie me donnait une erreur de type "unresolved package"

2020-04-07 11:29 UTC, hedi-guedidi commented
> 
> 
> PR depuis votre branche SVP (pour la prochaine fois).

Pour les PR est ce que ça va être de [Nompersonne]Dev vers dev ou  [Nompersonne]Dev vers master?

2020-04-07 12:12 UTC, EpicM commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/CalcData.java
> +public class CalcData {
A part pour la méthode populateDataFromJSON où je crois effectivement m'être trompé sur le type du paramètre (puisque Path ne couvre pas les chemins en http), je ne vois pas en quoi les autres headers seraient faux ? J'ai pris soin de regarder comment avaient fait les étudiants de l'ancien projet pour parser un CSV et c'est bien effectué à partir d'un Reader : [https://github.com/oliviercailloux/Teach-spreadsheets/blob/master/src/main/java/io/github/oliviercailloux/y2018/teach_spreadsheets/csv/CsvFileReader.java](url)

2020-04-07 17:38 UTC, EpicM commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/Course.java
> +            courseToBuild = new Course();
Je ne comprends pas cette remarque. Si j'ai bien compris vous voulez qu'on ne réinitialise pas courseToBuild. Supposons qu'on laisse le Builder dans l'état où il est avant construction : si l'on continue avec le même Builder pour construire deux objets (Teacher ou Course) sans le réinitialiser, on va juste se retrouver avec deux pointeurs qui feront référence au même objet Teacher ou Course, donc on est bien forcés de réinitialiser le Builder, sauf erreur de compréhension de ma part.

2020-04-09 14:08 UTC, merged

2020-04-10 11:42 UTC, oliviercailloux reviewed
Pour explication de OPT, voir SVP doc Projet dans le cours.

2020-04-10 11:42 UTC, oliviercailloux commented on .gitignore
> +bin/
Ceci n’a pas été modifié ?

2020-04-10 11:42 UTC, oliviercailloux commented on pom.xml
> +			<scope>compile</scope>
Pouvez-vous investiguer ? Il n’est pas souhaitable d’avoir une dépendance en compile alors qu’elle devrait être en test, ou il faut expliquer pourquoi c’est nécessaire.

2020-04-10 11:42 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/CalcData.java
> +	}
Je vous invite à placer les méthodes dans un ordre cohérent (OPT).

2020-04-10 11:42 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/CalcData.java
> +						coursePref.getCourse().getName().equals(otherCoursePref.getCourse().getName())) {
Cf. BP Style / Formatting SVP.

2020-04-10 11:42 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/CalcData.java
> +	public static CalcData newInstance(ImmutableSet<CoursePref> coursePrefs, Teacher teacher) {
Il faut accepter des paramètres plus généraux lorsqu’il n’y a pas d’inconvénient : Set conviendrait ici.

2020-04-10 11:42 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/CalcData.java
> +		return null;
Cf. BP null SVP.

2020-04-10 11:42 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/CalcData.java
> +			if (coursePref.getCourse().getName().contentEquals(courseName)) return coursePref;
Utiliser le `equals` habituel s’il n’y a pas de raison d’utiliser autre chose. (OPT)

2020-04-10 11:42 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/Course.java
> +        	checkNotNull(courseToBuild.name);
Cf. BP Exception SVP (OPT).

2020-04-10 11:42 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/Course.java
> +    		checkArgument(semester == 0 || semester == 1, "int must be 1 or 2.");
???

2020-04-10 11:42 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/Course.java
> +	public String toString() {
Cf. BP Eclipse config SVP.

2020-04-10 11:42 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/Course.java
> +		semester = 1;
Un meilleur choix serait d’initialiser à une valeur invalide, pour pouvoir obliger l’utilisateur à préciser le semestre. Si l’utilisateur oublie de le préciser, il n’y a pas de raison de privilégier le semestre 1 au 2, il s’agit sûrement d’une erreur qu’il faudrait plutôt signaler.

2020-04-10 11:42 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/CoursePref.java
> +        public Builder setCourse(Course course) throws NullPointerException {
Inutile d’annoncer `throws NPE`, sinon il faut le mettre partout. Cela doit être la convention par défaut que les arguments ne peuvent être nulls. Cf. BP Null.

2020-04-10 11:42 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/CoursePref.java
> +		return
Ceci renvoie une exception si `course` est `null`, on ne sait pas si c’est voulu ou si c’est un bug (et si c’est voulu, ce n’est pas le meilleur choix car on mélange deux manières d’indiquer une erreur, renvoi de `false` ou exception). De manière plus générale, il aurait mieux valu décider que cette méthode envoie une exception si incohérence, et rien sinon (auquel cas `checkCoherence` aurait été un meilleur nom), ce qui aurait permis d’envoyer une erreur plus claire à l’utilisateur. (OPT)

2020-04-10 11:42 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/CoursePref.java
> +    		this.coursePrefToBuild.prefCM = prefCM;
Voulez-vous vraiment autoriser cette préférence à être `null` ? Quelle serait la différence sémantique avec `UNSPECIFIED` ?

2020-04-10 11:42 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/CoursePref.java
> +        public Builder setCourse(Course course) throws NullPointerException {
Il est étrange d’autoriser à changer le cours et l’enseignant après coup, alors qu’on oblige de les préciser d’entrée de jeu. Je ne vois pas dans quel cas cela pourrait être utile, et cela a un cout en complexité. Si le cours ne peut pas être changé, alors on peut vérifier au fur et à mesure, lorsqu’on indique un nombre de groupes par exemple, que la valeur est cohérente vu le cours, et échouer plus rapidement si besoin. (OPT)

2020-04-10 11:42 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/Teacher.java
> +public class Teacher {
Il serait sympathique d’informer l’utilisateur que le minimum requis est `lastName`, cela ne me parait pas évident. (OPT)

2020-04-10 11:42 UTC, oliviercailloux commented on src/test/java/io/github/oliviercailloux/teach_spreadsheets/TeacherTests.java
> +	void testToString() {
Il convient surtout de tester que le builder refuse de créer un objet incohérent. C’est le seul aspect un peu subtil du code, et l’aspect le plus important. (Remarque valable pour toutes les classes concernées, bien sûr.)