Adding read functions to the LSO and APPRENTISSAGE tables.
Sarah-Elhelw/teach_spreadsheets pull request #12
Opened 2020-05-02 20:49 UTC by hedi-guedidi

2020-05-03 10:43 UTC, oliviercailloux requested changes
Si je vois bien, le code actuel de lecture d’une feuille « normale » (M1 Mathématiques, par exemple) est entièrement distinct du code de lecture d’une feuille Apprentissage. Il me semble au contraire que le code devrait être très similaire et donc très partagé, car ces deux formats ont suffisamment de similarité pour mériter un traitement commun. Plutôt que traiter les deux problèmes séparément, il faut que l’algorithme s’adapte aux en-têtes de colonnes qu’il trouve. Cela le rendra également plus robuste et plus général. Réfléchissez je vous prie à simplifier l’ensemble grâce à une approche unifiée en exploitant ce qui est commun. Par exemple, constatez que dans tous les cas, la découpe en semestres est très proche ; il faut lire les en-têtes par ligne pour chaque semestre jusqu’à trouver une cellule vide ; ensuite chaque enregistrement est constitué d’une ligne et d’autant d’entrées que d’en-têtes ; les noms des en-têtes sont souvent identiques…

Par ailleurs (mais c’est lié), l’approche actuelle est trop fragile pour être utile : si je lis bien, un simple changement du nombre de lignes cassera l’algorithme, qui se base sur des début de cadres pré-définis mais qui devraient plutôt être détectés. (Là aussi, la généralisation précédente sera utile.)

2020-05-03 10:43 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/read/CourseAndPrefReaderApprentissage.java
> +		cellText=cellText.trim();
Appliquez BP FORMAT SVP.

2020-05-03 10:43 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/read/CourseAndPrefReaderApprentissage.java
> +	private void setInfo(Table sheet, Teacher teacher,Set<CoursePref> coursePrefs,int currentCol, int currentRow, int semester) {
Je vous invite à éviter de modifier des paramètres, mais à plutôt renvoyer ce que la méthode calcule, c’est beaucoup plus clair pour le lecteur.

2020-05-03 10:43 UTC, oliviercailloux commented on src/test/java/io/github/oliviercailloux/teach_spreadsheets/read/CourseAndPrefReaderApprentissageTests.java
> +	void testreadSemester() throws Exception {
`…Read…`

2020-05-03 10:43 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/read/CourseAndPrefReaderLso.java
> +			/** As there is no case to choose the preference in the LSO tab, we assume it is A by default */
Il serait sympathique de spécifier cette hypothèse cruciale pour l’utilisateur dans l’en-tête de classe, car il ne verra très probablement pas ce commentaire caché dans le code.

2020-05-04 10:00 UTC, hedi-guedidi commented
Ces fonctionnalités (Lecture des onglets LSO et Apprentissage) ne vont pas faire l'objet d'un merge sur master pour faciliter le travail de l'équipe de l'année suivante.

2020-05-04 10:00 UTC, closed without merging