Correcting json package created in Iteration 2
Sarah-Elhelw/teach_spreadsheets pull request #19
Opened 2020-05-25 13:07 UTC by Sarah-Elhelw

La tâche associée à cette PR consiste en la correction du package json crée à l'itération 2 de java.
Les commentaires qu'on a cherché à satisfaire sont : https://github.com/Sarah-Elhelw/teach_spreadsheets/pull/9#discussion_r419760918, https://github.com/Sarah-Elhelw/teach_spreadsheets/pull/9#discussion_r419491991, https://github.com/Sarah-Elhelw/teach_spreadsheets/pull/9#discussion_r419496446 et https://github.com/Sarah-Elhelw/teach_spreadsheets/pull/9#discussion_r419501981.

Une issue que cherche à régler cette PR est https://github.com/Sarah-Elhelw/teach_spreadsheets/issues/16#issue-615225851.

Note :  les vérifications de l'intégration continue échouent à cause de tests unitaires qui ne fonctionnent pas dans un autre package (base) sur master même. Une autre PR se chargera de régler ce problème.

2020-05-31 22:23 UTC, oliviercailloux requested changes
Je maintiens que vous devriez pouvoir vous passer de cette conversion de vecteur à la main, que la bibliothèque json doit être capable de faire pour vous. Rendez-vous compte que ce serait une faiblesse inacceptable de cette bibliothèque que ce soit impossible. Votre test ne prouve pas cette nécessité.

2020-05-31 22:23 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/json/JsonRead.java
> +	 * @throws NullPointerException     if the parameter is null
Inutile (sinon il faut le mettre partout).

2020-05-31 22:23 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/json/JsonRead.java
> +			throw new IllegalArgumentException(e);
Une exception ici ne serait, je pense, pas un problème d’argument, mais un problème avec la bibliothèque json. Une `VerifyException` me semble donc appropriée, si on suppose que cela ne devrait pas arriver (supposition qui me semble raisonnable).

2020-05-31 22:23 UTC, oliviercailloux commented on src/test/java/io/github/oliviercailloux/teach_spreadsheets/json/JsonReadTests.java
> +		Course actualCourse = JsonRead.getSetOfCoursesInfo(formattedFileContent).asList().get(1);
Il serait prudent de vérifier également que l’ensemble renvoyé contient le bon nombre de cours.

2020-05-31 22:23 UTC, oliviercailloux commented on src/test/resources/io/github/oliviercailloux/teach_spreadsheets/json/Courses.json
> +{"rows":
Cette complexité est inutile. Votre fichier devrait être un JsonArray, pas un JsonObject. Donc commencer par un crochet ouvrant et se terminer par un crochet fermant, donc être un vecteur contenant des objets, pas un objet contenant un vecteur contenant des objets.

2020-05-31 22:23 UTC, oliviercailloux commented on src/test/resources/io/github/oliviercailloux/teach_spreadsheets/json/CoursesWithNullName.json
> +[
Voici un exemple de JsonArray, en fait.

2020-06-02 17:39 UTC, oliviercailloux requested changes

2020-06-02 17:39 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/json/JsonRead.java
> +		catch (JsonbException je) {
N’importe quelle RuntimeException devrait recevoir ce traitement.

2020-06-02 17:39 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/json/JsonWrite.java
> +			serialized = jsonb.toJson(courses.toArray());
Suivre les instructions du cours JsonB : utiliser une annotation sur la classe pour garantir et documenter l’ordre des champs.

2020-06-02 17:39 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/json/JsonWrite.java
> +	private static String serializeSet(Set<Course> courses) {
Réduire la visilibité de cette méthode, plus générale que les deux autres, semble bizarre. Pourquoi l’utilisateur ne voudrait-il pas récupérer le résultat sous forme de chaine, pour en faire ce qu’il veut ; alors qu’il peut mettre le résultat dans un fichier ou un writer ?

2020-06-02 17:39 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/json/JsonWrite.java
> +	public static void writeCoursesInAJsonFile(Path filePath, Set<Course> courses) throws IOException {
Une fois que l’autre méthode est publique, celle-ci ne semble plus utile : une méthode pour deux lignes de code, c’est rarement justifié. Même chose pour celle qui suit.

2020-06-02 17:39 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/json/JsonRead.java
> +	public static ImmutableSet<Course> getSetOfCoursesInfo(String fileContent) {
`fileContent` n’est pas un bon nom, puisqu’il n’y a pas de raison de restreindre l’usage au cas où le contenu vient d’un fichier ; `json` conviendrait.
`toCourses` est plus court et plus clair que `getSetOfCoursesInfo`, qui suggère qu’on récupère des informations à propos de cours plutôt que des cours.

2020-06-02 17:39 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/json/JsonWrite.java
> +			serialized = jsonb.toJson(courses.toArray());
pourquoi `toArray()` ?

2020-06-02 17:39 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/json/JsonRead.java
> +	private static void checkFormat(String textArray) {
Comme demandé précédemment, je vous invite à fournir un test unitaire qui illustre le problème qui se pose lorsque cette méthode n’est pas utilisée. Je continue à douter de sa pertinence.

2020-06-03 22:15 UTC, Sarah-Elhelw commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/json/JsonRead.java
> +	private static void checkFormat(String textArray) {
Pour illustrer le problème qui se pose, j'avais fait le test unitaire testDemonstratingNeedForFormatToArray() et vous l'avais soumis à l'avant dernière demande de review. 
J'ai de nouveau remis un test comparant, cette fois, les deux situations obtenues si on utilise ou pas checkFormat(). Par le test unitaire testDemonstratingNeedForCheckFormat(), je veux montrer que sans checkFormat(), notre programme se poursuit alors que le renvoi d'un ImmutableSet vide est faux, alors qu'avec checkFormat(), le programme s'arrête immédiatement car le contenu du fichier lu n'est pas une JsonArray comme exigé.

2020-06-07 08:26 UTC, oliviercailloux approved these changes
Votre démonstration est très intéressante. Il semble s’agir d’un bug dans la bibliothèque JsonB. Il faut encore un peu la peaufiner pour pouvoir leur faire connaitre ce bug. Veuillez rendre ce test indépendant de votre code, en démontrant simplement qu’un fichier mal formaté renvoie un ensemble vide au lieu d’une erreur. J’imagine que cela se produit avec toute autre chose qu’un ensemble de cours. Simplifiez le test autant que possible (par exemple le fichier exemple pourrait être plus simple). FUTURE.

Pour ce qui nous concerne, (re-)mettez le check en private et intégré dans `toCourses`.

Ok pour fusion moyennant les qqs changements restants indiqués ici.

2020-06-07 08:26 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/json/JsonDeserializer.java
> +		 */
À mon avis, commentaire inutile, c’est une technique classique qui ne requiert pas d’explication spécifique. OPT.

2020-06-07 08:26 UTC, oliviercailloux commented on src/test/java/io/github/oliviercailloux/teach_spreadsheets/json/JsonDeserializerTests.java
> +		final Path path = Path.of(resourceUrl.toURI());
J’ai ajouté une note dans BP Eclipse pour ce cas.

2020-06-07 13:29 UTC, merged