Class AgregatedData
Sarah-Elhelw/teach_spreadsheets pull request #21
Opened 2020-05-25 13:53 UTC by Sarah-Elhelw

La tâche associée à cette PR consiste en la création de la classe AgregatedData (dans le package base).

On pourra se référer au diagramme de classe accessible par ce lien : https://github.com/Sarah-Elhelw/teach_spreadsheets/blob/master/Doc/Images/Class_assignment.PNG.

Note : les vérifications de l'intégration continue échouent à cause de tests unitaires qui ne fonctionnent pas dans un autre package (base) sur master même. Une autre PR se chargera de régler ce problème.

2020-05-25 14:22 UTC, oliviercailloux requested changes
Il convient de restaurer les tests en priorité. Redemandez une review par la suite SVP.

2020-05-28 18:45 UTC, Sarah-Elhelw commented
Pour ce qui est de votre remarque suivante de l'itération 4 d'UML "AggregatedData devrait pouvoir être également créé à partir d’un ensemble de CoursePref pour plus de généralité. On clarifierait la conception en liant directement AggData à un ensemble de CoursePref, en passant outre CalcData.". Nous avons choisi de créer une issue (https://github.com/Sarah-Elhelw/teach_spreadsheets/issues/22#issue-626729768) associée afin de la régler par la suite. En effet, le binôme Hedi-Mike de l'itération 3 de java a besoin d'une classe AggregatedData comme étant un ensemble de CalcData afin de réaliser sa tâche et vous soumettre leur PR.

2020-06-09 06:58 UTC, oliviercailloux requested changes

2020-06-09 06:58 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/base/AggregatedData.java
> +			tempCourses = new LinkedHashSet<>();
Initialisation explicite de tous les champs SVP.

2020-06-09 06:58 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/base/AggregatedData.java
> +						"You cannot add twice all the preferences of a teacher.");
Préciser le teacher dupliqué dans le message, tant que vous l’avez sous la main, ça aidera en cas de problème.

2020-06-09 06:58 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/base/AggregatedData.java
> +		return calcDatas;
Ceci n’est pas correct, il ne faut pas donner votre ensemble non protégé à votre appelant (même chose pour getCourses)

2020-06-09 06:58 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/base/AggregatedData.java
> +	public Set<CoursePref> getCoursePrefs(Course course) {
Appliquez BP Local design, method return types.

2020-06-09 06:58 UTC, oliviercailloux commented on src/test/java/io/github/oliviercailloux/teach_spreadsheets/base/AggregatedDataTests.java
> +		});
Pourquoi cette complexité soudaine ?

2020-06-09 19:14 UTC, oliviercailloux approved these changes
Ok moyennant commentaires restants.

2020-06-09 19:14 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/base/AggregatedData.java
> +								+ calcData.getTeacher().getFirstName() + " " + calcData.getTeacher().getLastName());
`calcData.getTeacher()` aurait convenu et est plus simple (OPT)

2020-06-09 19:14 UTC, oliviercailloux commented on src/test/java/io/github/oliviercailloux/teach_spreadsheets/base/AggregatedDataTests.java
> +		aggregatedDataBuilder.build();
Vous vouliez dire, j’imagine, `assertDoesNotThrow()` ?

2020-06-09 19:16 UTC, Sarah-Elhelw commented on src/test/java/io/github/oliviercailloux/teach_spreadsheets/base/AggregatedDataTests.java
> +		aggregatedDataBuilder.build();
C'est en effet ce que je voulais faire avec assertAll().

2020-06-09 19:58 UTC, merged