Adding equals methods in Teacher and Course classes
Sarah-Elhelw/teach_spreadsheets pull request #23
Opened 2020-05-29 12:27 UTC by Sarah-Elhelw

La tâche associée à cette PR consiste en l'ajout de la méthode equals dans les classes Teacher et Course.
Les modifications suivantes ont donc été apportées au code : 
- ajout de equals et de hashCode dans Teacher et Course
- correction des lignes de code dans le projet nécessitant les méthodes equals définies
- correction des tests unitaires du code, au vu des modifications apportées, pour qu'ils continuent de fonctionner
- ajout de tests unitaires pour tester les méthodes equals ajoutées.

2020-05-31 22:00 UTC, oliviercailloux requested changes

2020-05-31 22:00 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/base/Course.java
> +		 * that has the same name no matter the semester or study level.
Ce commentaire, définissant un aspect important de cette classe, doit être visible des utilisateurs de cette classe.

L’égalité doit entrainer l’interchangeabilité : aucun changement de comportement du code notable ne doit survenir en remplaçant une instance par une instance qui lui est égale. Ce n’est pas le cas ici, car un cours peut égaler un autre en ayant un nombre de groupes ou de minutes distinct. Ceci pourrait créer des bugs subtils et doit donc être évité.

2020-05-31 22:00 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/base/Course.java
>  		return MoreObjects.toStringHelper(this).add("name", name)
(Tant qu’on y est.) Ceci n’est pas très utile : si l’utilisateur de cette instance veut uniquement afficher son nom, il lui suffit d’appeler `getName()`. `toString()` devrait afficher une information complète, pour permettre de comprendre vraiment ce qui se passe si on le souhaite, en cas de bug par exemple.

2020-05-31 22:00 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/base/Teacher.java
> +		 * e-mail.
Même problème.

2020-05-31 22:00 UTC, oliviercailloux commented on src/test/java/io/github/oliviercailloux/teach_spreadsheets/base/CourseTests.java
> +	void testEquals() {
Test inutile à mon avis : ce code est trop simple pour échouer. OPT

2020-06-01 11:19 UTC, Sarah-Elhelw commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/base/Course.java
>  		return MoreObjects.toStringHelper(this).add("name", name)
Je ne comprends pas ce que vous voulez dire. Pourriez-vous plus détailler votre commentaire SVP ? toString() renvoie actuellement l’ensemble des valeurs des attributs d’un Course, pas seulement son nom.
Par ailleurs, on souhaiterait régler ce point sur une autre PR, la PR actuelle ne servant qu’à réaliser la tâche suivante : ajouter la méthode equals() dans Course et Teacher car nous en avons besoins dans d’autres PR.

2020-06-02 17:47 UTC, oliviercailloux requested changes
Il semble que mes commentaires n’aient pas tous été pris en compte, sauf erreur de ma part.

2020-06-02 17:47 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/base/Course.java
>  		return MoreObjects.toStringHelper(this).add("name", name)
Vous avez raison, j’ai mal lu (une partie de ce code était caché).

2020-06-02 18:04 UTC, Sarah-Elhelw commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/base/Course.java
> +		 * that has the same name no matter the semester or study level.
Nous avons répondu à ce commentaire en ajoutant des verify dans les méthodes equals de Course et Teacher. Ainsi, nous vérifions bien l'égalité de tous les attributs. De plus, les verify permettent de faire échouer le test rapidement car on considère que d'après nos critères d'égalité des professeurs et des cours, s'il n'y a pas égalité sur tous les attributs, il y a un bug qui s'est glissé dans notre programme.

2020-06-02 18:06 UTC, Sarah-Elhelw commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/base/Teacher.java
> +		 * e-mail.
Nous avons répondu à ce commentaire en mettant le commentaire dans la javadoc de la méthode, le commentaire est ainsi visible d'un utilisateur de la classe.

2020-06-02 18:08 UTC, Sarah-Elhelw commented on src/test/java/io/github/oliviercailloux/teach_spreadsheets/base/CourseTests.java
> +	void testEquals() {
Nous avons répondu à ce commentaire en supprimant les tests unitaires dans CourseTests et TeacherTests.

2020-06-04 08:46 UTC, oliviercailloux requested changes
Vous avez raison (pour la deuxième fois !), vous avez pris mes commentaires en compte. J’ai cru que les méthodes equals n’avaient pas changé. Désolé pour la confusion.

Les verify dans equals sont une idée intéressante, mais à mon avis inadaptée. Il sera très difficile de vous assurer que cette condition est toujours vérifiée avant d’invoquer equals : les violations de cette condition viendront généralement du monde extérieur, que vous ne maitrisez pas. Par exemple, cette condition pourrait échouer lors de la lecture de feuilles de calcul, si elles sont incohérentes. 

Autrement dit, le test est à un endroit de trop bas niveau. Il faut, lorsque c’est possible, donner à l’appelant un moyen de détecter un problème avant de lancer une exception : elle doit être le dernier ressort. Dans ce cas, il serait très difficile et peu pratique pour l’appelant de tenter de détecter le problème systématiquement avant l’utilisation de equals.

Pour l’expliquer autrement, dans l’exemple précédent, il serait bon de faire savoir à l’utilisateur final que la condition échoue et à cause de quelle feuille de calcul (via un moyen approprié dans le GUI, sans-doute) ; lancer une exception dans la méthode equals rendra une telle entreprise délicate.

Un autre problème est que cette vérification ne suffit pas, de toute façon, ou c’est dangereux de supposer qu’elle suffit. Mettre vos cours dans une collection ne garantit pas nécessairement que equals sera appelé sur chaque paire de cours (ça dépend de la structure). Donc il faudra de toute façon implémenter une vérification supplémentaire, systématique, ailleurs.

On conseille généralement de ne pas essayer d’être malin dans equals : cette méthode est trop fondamentale pour du traitement de haut niveau.

Je vous invite à implémenter equals plus simplement, en testant l’égalité terme à terme.

Il serait sans-doute bon d’implémenter une vérification similaire à celle que vous proposez ici dans les classes où on regroupe des ensembles de cours et où on veut s’assurer de leur cohérence. (OPT)

2020-06-07 08:31 UTC, oliviercailloux approved these changes

2020-06-07 08:31 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/base/Teacher.java
> +		}
Optimisation de détail inutile. OPT.

2020-06-07 09:35 UTC, merged