Adding a Gui
Sarah-Elhelw/teach_spreadsheets pull request #28
Opened 2020-06-07 20:35 UTC by hedi-guedidi

Remarques : 
-La fonction main qui se trouve dans la classe Controller permet de lancer et tester la gui.
-La gui a été testée sous Windows 10 et Mac OS.
-On est en attente du merge de la PR #18 pour ajouter un Course à chaque TeacherAssignment créé.

2020-06-09 06:30 UTC, oliviercailloux requested changes
Voudriez-vous me fournir un lien vers un diagramme adéquat pour que je dispose d’une vue de haut niveau de votre implémentation, afin de comprendre votre approche facilement ? Je continuerai la review ensuite.

2020-06-09 06:30 UTC, oliviercailloux commented on pom.xml
> +<project xmlns="http://maven.apache.org/POM/4.0.0"
Minimisez SVP les changements dans le POM, tous ces changements ne semblent pas nécessaires pour votre implémentation. (Ou expliquez.)

2020-06-09 19:21 UTC, hedi-guedidi commented on pom.xml
> +<project xmlns="http://maven.apache.org/POM/4.0.0"
J'ai essayé de minimiser les changements dans le POM.Les écarts restants sont normalement dus à : l'ajout des profiles et librairies pour la gui, Le Format et la suppression des lignes vides inutiles.

2020-06-10 13:56 UTC, EpicM commented
> Voudriez-vous me fournir un lien vers un diagramme adéquat pour que je dispose d’une vue de haut niveau de votre implémentation, afin de comprendre votre approche facilement ? Je continuerai la review ensuite.

Voici la documentation correspondante : https://github.com/Sarah-Elhelw/teach_spreadsheets/tree/master/Doc#gui-classes

2020-06-11 09:13 UTC, oliviercailloux requested changes
Difficile d’être sûr que je comprends bien votre intention, car le diagramme n’est pas à jour comparé à nos discussions, ni à votre implémentation, il me semble. En particulier, il me faudrait une explication de haut niveau sur votre approche des préférences dans le modèle, puisque conformément à notre discussion précédente, il ne suffit pas de gérer les préférences comme deux ensembles disjoints. Si vous souhaitez avancer rapidement sur cette PR, vous pouvez décider de prendre de l’avance sur votre prochaine livraison UML en mettant déjà votre diagramme à jour.

Il me semble que votre vue ou modèle appellent le contrôleur, et utilisent son information pour se mettre à jour, ce qui n’est pas une bonne idée. Ce choix vous conduit à déclarer des champs et méthodes statiques, qui ne devraient pas l’être. Cette approche utilisant des champs statiques comme variables globales ne suit pas les principes orienté-objet, puisque tout est visible de tous. 

Comme son nom l’indique, le contrôleur doit être maitre, c’est lui qui doit appeler et mettre à jour les autres composants. Il doit s’enregistrer en tant que listener sur la vue, et décider lui-même de ce qu’il met à jour lorsque la vue l’informe d’un changement.

2020-06-11 09:13 UTC, oliviercailloux commented on pom.xml
> +			<id>release</id>
Je doute que le profil release vous soit nécessaire (ou expliquez).

2020-06-11 09:13 UTC, oliviercailloux commented on pom.xml
> -	</build>
Ceci est utile, comme indiqué par le commentaire, je ne vois pas de raison de l’enlever.

2020-06-11 09:13 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/gui/Controller.java
> +		Model.initData();
Respectez les conventions de nommage SVP.

2020-06-11 19:02 UTC, hedi-guedidi commented
**Copie de l'échange par mail :** 

**Mike :** 
Nous avons quelques points à préciser :
- Nous avons justement mis à jour notre diagramme conformément à notre nouvelle implémentation. Il est possible que nous ayons oublié des détails cependant puisque vous pensez que le diagramme n'est pas à jour.

- Concernant les préférences dans le modèle, nous avons justement créé une nouvelle structure, CoursePrefElement, qui nous permet de gérer les préférences comme deux ensembles disjoints. Une instance de CoursePrefElement représente un et un seul élément du tableau dans l'interface graphique.

- Dans notre code actuel, "l'enregistrement" du contrôleur comme listener se fait à travers ses fonctions de callback. La vue crée les listeners et appelle la fonction de callback du contrôleur pour gérer l'input de l'utilisateur.
La flèche use entre la vue et le contrôleur dans le diagramme indique cet "enregistrement". Est-ce que vous voudriez que les listeners soient entièrement implémentés dans le contrôleur sans fonction de callback ?

- Concernant les champs et méthodes statiques, on va voir comment faire pour respecter les principes de l'orienté objet. Effectivement on a négligé cet aspect.

**Vous :** 

Merci pour ces précisions utiles. Ok pour votre diagramme, je n’avais pas regardé suffisamment en détail et n’avais pas vu entre autres la modification du modèle.

La vue ne doit pas connaitre le contrôleur, elle doit fonctionner indépendamment de lui. Autrement dit, on doit pouvoir changer de contrôleur sans changer aucunement le code de la vue. La vue doit avertir ses listeners lorsqu’il y a un changement (et en pratique, le listener peut être le contrôleur, mais la vue ne le sait pas). Cela ne donne pas pour autant le droit à la vue de mettre quoi que ce soit à jour (y compris elle-même) en obtenant des informations du contrôleur (ou d’ailleurs). C’est le contrôleur qui doit le faire : push, pas pull.

Veuillez reporter ces informations dans la PR (éventuellement après mise à jour lorsque vous aurez corrigé les problèmes restants), pour que j’aie tous vos commentaires au même endroit.

2020-06-11 20:03 UTC, hedi-guedidi commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/gui/Controller.java
> +		Model.initData();
Pourriez-vous nous fournir plus de détails SVP ?

2020-06-13 09:54 UTC, oliviercailloux requested changes
Il me semble pertinent de vous fournir encore des commentaires de haut niveau à partir de votre diagramme, à ce stade. Comme je n’ai pas regardé le code en détail, certains commentaires pourraient être inappropriés. Je vous laisse en juger et corriger ce qui vous semble devoir être corrigé, ou commenter en réponse ici. Je regarderai le code ensuite.

- View#exit : cette méthode est au moins mal nommée. La vue ne doit pas être capable de quitter l’application, au mieux, on peut lui demander de fermer la fenêtre. C’est le contrôleur qui décide de quitter. (En pratique, le contrôleur doit donc enregistrer un listener sur l’action de fermeture de la fenêtre pour en être averti.)
- Ctrl#createAssignments ; #setModelData : ces méthodes ne devraient pas être publiques et pas pouvoir être appelées de l’extérieur, j’imagine (ou je ne comprends pas pourquoi).
- Ctrl#callbackListener : le nom de cette méthode devrait plutôt indiquer ce qu’elle fait.
- Model#updateSet ; CPE#getTableItem ; et qqs autres : le modèle (et donc CPE, partie du modèle) doit être indépendant de la vue, pour clarté conceptuelle et réutilisabilité. Ils ne doivent donc pas faire référence (ni dans leur code, ni conceptuellement) à la notion de TableItem. C’est la vue ou le contrôleur qui doit traduire les informations des TableItems en informations conceptuellement claires de haut niveau telles que des préférences. La vue doit, autant que possible, fournir des informations conceptuellement claires au contrôleur en masquant la complexité des TableItems ou autres éléments de Gui ; si ce n’est pas approprié, c’est alors le contrôleur qui parse et extrait les informations en dernier recours.

2020-06-14 12:53 UTC, hedi-guedidi commented
Les modifications faites suite à vos commentaires : 
* La fonction exitApplication() est déplacée dans le Controller.Cette fonction va être appelée par le main du programme (partie non encore entamée) afin de fermer le programme et par conséquence la gui.
* Les fonctions Ctrl#createAssignments ; #setModelData sont maintenant de visibilité private.
* Le nom de Ctrl#callbackListener a été changé en updateModelAndView.
* Adaptation du code pour séparer la vue du modèle.Les fonctions qui s'occupent de la mise à jour du modèle sont maintenant dans le controller.

2020-06-15 17:01 UTC, oliviercailloux approved these changes
Vous pouvez considérer tous les commentaires restants comme OPT.

Ok pour fusion moyennant simplification du exitApplication comme discuté : submit ne fait qu’écrire, et fermer la fenêtre ferme l’application.

FUTURE : enlever bouton submit ou ajouter une vérification que les derniers changements ont été écrits et demander une confirmation de quitter si non.

2020-06-15 17:01 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/gui/Model.java
> +		}
Veuillez simplifier ce code en lisant le contrat de `Set#add`.

2020-06-15 17:01 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/gui/View.java
> +		}
C’est le contrôleur qui doit faire tourner cette boucle.

2020-06-15 17:01 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/gui/View.java
> +	public void moveTableItem(TableItem tableItem, String[] texts, boolean toChosenPreferences) {
Pas de référence publique à TableItem si possible, les ordres venant du contrôleur devraient être de plus haut niveau.

2020-06-15 17:01 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/gui/View.java
> +	public void populateAllPreferences(List<String[]> stringsToShow) {
Pas de vecteur dans les méthodes publiques, on privilégie les structures mieux orientées objet dans ce cours, et cette liste de liste de strings est de trop bas niveau. Il semble qu’une liste de CPE conviendrait ici.

2020-06-15 17:01 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/gui/View.java
> +		submit.setLayoutData(new GridData(SWT.END, SWT.CENTER, false, false));
Est-il vraiment utile de créer un composite géré par un GridLayout pour y mettre un seul élément, plutôt que mettre le bouton directement dans le parent ? Documenter brièvement, si oui.

2020-06-15 17:01 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/gui/View.java
> +		buttonSubmit.setText("Submit ");
Si l’espace final est utile, documenter, sinon, le retirer.

2020-06-15 17:01 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/gui/CoursePrefElement.java
> +	public static CoursePrefElement newInstance(CourseType courseType1, CoursePref coursePref1) {
Ces noms sans 1 final seraient plus lisibles pour l’appelant (qui se demande pourquoi 1 comme s’il y avait un 2 quelque part).

2020-06-15 17:01 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/gui/CoursePrefElement.java
> +	}
Il serait plus lisible d’indiquer explicitement les paramètres requis (c-à-d type et pref).

2020-06-15 17:01 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/gui/CoursePrefElement.java
> +	private CoursePref coursePref;
`final` clarifierait la garantie d’immuabilité.

2020-06-15 17:01 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/gui/CoursePrefElement.java
> +		checkNotNull(coursePref1);
Devrait être dans le constructeur, pour clarifier les garanties.

2020-06-15 17:01 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/gui/Controller.java
> +	public static Controller newInstance(View view, Model model) {
Le contrôleur devrait créer la vue et le modèle. C’est lui qui en est responsable.

2020-06-15 17:01 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/gui/Controller.java
> +	private void registerListener(Listener listener, Widget widget, int eventType) {
Retirer cette méthode d’une ligne.

2020-06-15 17:01 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/gui/Controller.java
> +		checkArgument(source == view.getAllPreferencesTable() || source == view.getChosenPreferencesTable(),
Relire les diapos sur les exceptions pour mieux choisir le type de cette exception.

2020-06-15 17:01 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/gui/Controller.java
> +	 *         the user to exit the application.
Ceci n’a pas l’air vrai… Éviter la documentation de ce type, facilement périmée. Mieux nommer les méthodes permet de pouvoir s’en passer.

2020-06-15 17:01 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/gui/Controller.java
> +	private void updateModelAndView(TableItem item, boolean toChosenPreferences) {
`updateModelAndView` est peu discriminant : c’est ce qu’un contrôleur est censé faire en réponse à n’importe quel événement. `itemClicked` aurait pour avantage d’annoncer clairement l’événement auquel on répond ici.

2020-06-15 17:01 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/gui/Controller.java
> +		checkNotNull(model);
Ces vérifications ne me semblent pas utiles, il devrait être facilement visible que la vue et le modèle ne peuvent être nuls ici. OPT.

2020-06-21 17:28 UTC, merged