Class OdsSummarizer
Sarah-Elhelw/teach_spreadsheets pull request #29
Opened 2020-06-08 15:22 UTC by Sarah-Elhelw

La tâche associée à cette PR consiste en l'amélioration des classes GlobalAssignment et TeachersPreferences entamées pendant l'itération 2. Nous avons décidé, pour éviter la duplication de code, de fusionner ces deux classes pour ne travailler que sur OdsSummarizer.
Les deux principales améliorations sont:
- la suppression des nombreuses duplications de code
- le travail sur l'esthétique de l'ods crée. Le fichier crée sera esthétiquement semblable au fichier OdsSummarizer.ods qu'on peut trouver ici : https://github.com/Sarah-Elhelw/teach_spreadsheets/tree/it3-writing/src/test/resources/io/github/oliviercailloux/teach_spreadsheets/write

Nous avons également cherché à satisfaire les commentaires suivants : https://github.com/Sarah-Elhelw/teach_spreadsheets/pull/15#discussion_r420309831, https://github.com/Sarah-Elhelw/teach_spreadsheets/pull/15#discussion_r420316604, https://github.com/Sarah-Elhelw/teach_spreadsheets/pull/15#discussion_r420317021 et https://github.com/Sarah-Elhelw/teach_spreadsheets/pull/15#discussion_r420317421.

On pourra se référer au diagramme de classe accessible par ce lien : https://github.com/Sarah-Elhelw/teach_spreadsheets/blob/master/Doc/Images/Class_ODS_Write.PNG

2020-06-11 08:30 UTC, oliviercailloux requested changes

2020-06-11 08:30 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/assignment/TeacherAssignment.java
> +	public int getCountGroups(String group) {
Introduisez un enum `SubCourseKind` avec ces cinq valeurs SVP.

2020-06-11 08:30 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/write/OdsSummarizer.java
> +	 * will be provided to create the summarized ods file. In this class, the
Une classe doit avoir un sens indépendant du reste du projet, pour décomposer les problèmes. La doc ne doit donc pas faire référence au fonctionnement du projet global, qui doit pouvoir être déterminé indépendamment.

2020-06-11 08:30 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/write/OdsSummarizer.java
> +	 * to display.
Je ne vois pas l’avantage de l’optionnel, par rapport à un ensemble vide, qui indiquerait tout autant l’absence d’information d’affectation et est plus simple à manipuler.

2020-06-11 08:30 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/write/OdsSummarizer.java
> +		}
Envisagez de remplacer ces quatre lignes par une seule avec stream() et map(). OPT.

2020-06-11 08:30 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/write/OdsSummarizer.java
> +			Optional<Set<TeacherAssignment>> teachersAssigned) {
Même chose, un `Set` vide plutôt qu’un `Optional` vide produira le même effet et est plus simple.

2020-06-11 08:30 UTC, oliviercailloux commented on src/test/java/io/github/oliviercailloux/teach_spreadsheets/write/OdsSummarizerTests.java
> +					tableCreated.getCellByPosition("I8").getDisplayText());
Pourquoi ne pas plutôt tester l’égalité de toute la feuille produite, ou un rectangle de cette feuille (toutes les cellules de 1à 12 et de A à H) ?

2020-06-12 08:57 UTC, Sarah-Elhelw commented on src/test/java/io/github/oliviercailloux/teach_spreadsheets/write/OdsSummarizerTests.java
> +					tableCreated.getCellByPosition("I8").getDisplayText());
Nous avons essayé de tester l’égalité d’un rectangle qui s’étend des cellules A1 à J15 (afin de couvrir l’ensemble du tableau crée) en comparant deux objets de type CellRange, puis nous avons essayé de tester l’égalité de toute la feuille produite en comparant deux objets de type Table et enfin nous avons essayé un plus haut niveau en comparant deux objets de type SpreadsheetDocument. Cependant, tous ces tests échouent car la méthode equals n’a pas été implémentée dans les classes CellRange, Table et SpreadsheetDocument (elles sont seulement héritées de Object qui propose donc une implémentation qui ne convient pas ici).
Si vous le souhaitez, voici les liens vers la documentation de ces classes :
- CellRange : https://odftoolkit.org/api/simple/org/odftoolkit/simple/table/CellRange.html
- Table : https://odftoolkit.org/api/simple/org/odftoolkit/simple/table/Table.html
- SpreadsheetDocument : https://odftoolkit.org/api/simple/org/odftoolkit/simple/SpreadsheetDocument.html

Nous sommes donc restées sur notre ancienne proposition.

2020-06-13 10:08 UTC, oliviercailloux approved these changes

2020-06-13 10:08 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/assignment/TeacherAssignment.java
> +			throw new IllegalArgumentException("The argument must be CM, TD, TP, CMTD or CMTP.");
`VerifyException` me semble approprié ici : vous pouvez supposer que personne n’a modifié votre enum et que ces cinq valeurs sont donc les seules possibles. OPT.

2020-06-13 10:08 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/base/SubCourseKind.java
> +public enum SubCourseKind {
Envisager d’utiliser cet enum plus systématiquement pour simplifier le code en général. FUTURE.

2020-06-13 10:08 UTC, oliviercailloux commented on src/test/java/io/github/oliviercailloux/teach_spreadsheets/write/OdsSummarizerTests.java
> +			assertEquals(table.getCellByPosition("C4").getDisplayText(),
Je maintiens ma suggestion. Votre code fait sept fois la même chose, il faut donc le remplacer par une boucle. Je suggère une double boucle qui parcours le rectangle de A à H et de 1 à 12 et qui fait l’assert en question. Ceci ne requiert pas d’implémentation de `#equals`. OPT.

2020-06-13 12:15 UTC, merged