Testing the time for writing classes
Sarah-Elhelw/teach_spreadsheets pull request #36
Opened 2020-06-15 11:51 UTC by Semida-Buzdugan

Cette classe permet de tester le temps nécessaire à l'écriture de 100 professeurs et 100 cours. 
Sur mon Eclipse, ce test prend 7 secondes en moyenne.

2020-06-15 17:28 UTC, hedi-guedidi commented
Premier essai :
![image](https://user-images.githubusercontent.com/61390793/84687310-d5059480-af3d-11ea-89c5-b1db32c6c200.png)
Deuxième essai : 
![image](https://user-images.githubusercontent.com/61390793/84687422-04b49c80-af3e-11ea-8a1c-9715dc2c54cc.png)
Le test testWriting100 prend approximativement 18s.
Mon PC est sous Windows 10, processeur i5, 8GB RAM

2020-06-15 18:25 UTC, hedi-guedidi approved these changes

2020-06-15 19:19 UTC, Sarah-Elhelw commented
![image](https://user-images.githubusercontent.com/45911833/84696721-32eda880-af4d-11ea-8bc3-33c9c716ed1a.png)

Le test testWriting100 prend près de 21s.
Mon PC est sous Windows 10, processeur i5, 8,00 Go de RAM (vitesse de la RAM : 1867 MHz), SSD.

2020-06-15 20:45 UTC, hedi-guedidi commented
![image](https://user-images.githubusercontent.com/61390793/84704249-d349ca00-af59-11ea-8d3f-1b22f3f3558e.png)
Mon PC est sous windows 10 ,processeur i5, 8GB RAM,HDD (disque dur normal).

2020-06-15 20:55 UTC, hedi-guedidi commented
![image](https://user-images.githubusercontent.com/61390793/84705173-4acc2900-af5b-11ea-95bb-47abc7f1746b.png)
Mon PC est sous windows 10 ,processeur i5, 8GB RAM,HDD (disque dur normal).

2020-06-15 21:02 UTC, hedi-guedidi approved these changes

2020-06-15 21:19 UTC, Sarah-Elhelw commented
![image](https://user-images.githubusercontent.com/45911833/84706980-33db0600-af5e-11ea-97d2-cb4f12d5680e.png)
![image](https://user-images.githubusercontent.com/45911833/84707147-7866a180-af5e-11ea-9c14-05dc9374f69e.png)
Mon PC est sous Windows 10, processeur i5, 8,00 Go de RAM (vitesse : 1867 MHz), SSD.

2020-06-16 06:57 UTC, inesdraredja commented
![Capture d’écran 2020-06-16 à 08 56 49](https://user-images.githubusercontent.com/61460880/84741451-6c570000-afaf-11ea-867e-268168e7e729.png)

2020-06-16 06:59 UTC, inesdraredja commented
![Capture d’écran 2020-06-16 à 08 58 47](https://user-images.githubusercontent.com/61460880/84741606-9d373500-afaf-11ea-8800-7f4a8436eb8b.png)

2020-06-16 07:19 UTC, EpicM commented
38.601 secondes pour l'ensemble des tests sur OdsSummarizerTests. Je suis sur un HDD.

2020-06-16 08:51 UTC, Semida-Buzdugan commented
![Captură de ecran din 2020 06 16 la 10 45 20](https://user-images.githubusercontent.com/61501658/84752929-b1366300-afbe-11ea-8a2d-b805d4f18524.png)
![Captură de ecran din 2020 06 16 la 10 45 38](https://user-images.githubusercontent.com/61501658/84752942-b693ad80-afbe-11ea-97f5-4d3bf6c213f2.png)

iMac 
Processeur 3,2 GHz Intel Core i5
Memoire 8 GB 1600 MHz DDR3

2020-06-16 18:47 UTC, oliviercailloux requested changes
Intéressant.

Il semble clair qu’à court terme, à moins que la constatation soit incorrecte et à moins d’arriver à résoudre ce problème, on devra donc conserver le bouton Submit. Merci de préciser les raisons de cette conclusion dans votre doc, pour que ça ne se perde pas.

Concentrons-nous sur testW100S, qui me semble le plus pertinent pour notre question. Plus précisément, il faut uniquement compter le temps d’écriture, donc uniquement le try dans ce test.

Il est peu utile de tester sur des machines différentes : on veut un ordre de grandeur.

Il est très étonnant qu’écrire un tel fichier prenne une dizaine de secondes. Il serait intéressant de trouver ce qui prend tant de temps. 

Pouvez-vous m’indiquer la taille du fichier de sortie ?

Pouvez-vous ajouter des LOGGER.info(…) un peu partout dans votre test et dans OdsSummarizer#createSummary() pour déterminer quels appels prennent beaucoup de temps ? Je soupçonne qu’une chose en particulier doit causer une grande partie du temps total passé.

2020-06-17 15:31 UTC, hedi-guedidi commented
Voici les logs obtenus :
![image](https://user-images.githubusercontent.com/61390793/84917569-cb0b9f00-b0bf-11ea-8f81-3d38049580a2.png)
* Le problème vient de l'écriture d'un fichier avec pleins (100) d'affectations sur le disque.
* Le test testWritingSummaryAndAssignmentsPerTeacher100() a été supprimé comme convenu ce matin.
* La taille du fichier généré est de 85 Ko.

2020-06-19 15:10 UTC, oliviercailloux approved these changes
Je suggère de retirer ces appels à Time bidule, ils sont peu utiles puisque le logger indique le temps passé, et nuisibles car orientant possiblement vos successeurs vers une mauvaise piste.

Documentez en Javadoc que ces tests ne servent qu’à mesurer le temps d’écriture.

Je maintiens ma suggestion précédente d’utiliser des loggers pour déterminer plus précisément ce qui prend tant de temps, mais ceci peut être laissé pour le futur.

2020-06-20 13:10 UTC, hedi-guedidi commented
Ajout de ce point dans le fichier Advice.adoc .

2020-06-20 13:31 UTC, merged