Possible bug on Jsonb deserializer
Sarah-Elhelw/teach_spreadsheets pull request #39
Opened 2020-06-22 10:50 UTC by Sarah-Elhelw

La tâche associée à cette PR consiste en l'ajout d'une classe Person très simple contenant une méthode  toPersons qui a une fonction similaire à toCourses dans JsonDeserializer : elle lit un json array string et renvoie une liste immuable de personnes. Cette classe est munie de getters, setters et toString facilitant le débuggage. Le test unitaire présente 2 cas : le 1er présente le possible bug trouvé et le 2ème sert de témoin pour prouver qu'il n'y a pas de problème provenant de la classe Person, de toPersons ou des lignes de code dans le test.

L'issue associée à cette PR est : https://github.com/Sarah-Elhelw/teach_spreadsheets/issues/25.

On pourra se référer au diagramme de classe suivant : https://raw.githubusercontent.com/Sarah-Elhelw/teach_spreadsheets/master/Doc/Images/Class_Json_Deserializer.PNG.

2020-06-22 18:03 UTC, oliviercailloux requested changes
Pour un rapport de bug auprès de l’équipe de JSON-B, il convient d’encore simplifier `Person` si possible, en utilisant un seul attribut `name` au lieu de deux. Transférer le contenu de `toPersons` dans le test, enlever la gestion des exceptions pour se concentrer sur l’essentiel. Utiliser une variable string dans le test lui-même (se passer des fichiers) pour rendre le bug visible en regardant seulement une méthode.

Indiquez SVP si l’absence d’échec rapide se produit avec n’importe quel format incorrect (par exemple en enlevant une accolade fermante ou un crochet fermant), ou s’il est spécifique à ce format. Il pourrait être pertinent, en fonction de la réponse à cette question, de remplacer le test “RightFormat” par un test qui illustre que le comportement diffère avec un autre format d’entrée par exemple. OPT.

2020-06-22 21:54 UTC, Sarah-Elhelw commented
Il semble que ce possible bug de la bibliothèque se produise lorsqu'on ne donne pas une json array à toPersons. Tout autre format de json (et donc correct selon la syntaxe json) renvoie une liste vide. Un formatage incorrect (selon la syntaxe json) provoque un échec rapide.

2020-06-24 07:49 UTC, oliviercailloux approved these changes

2020-06-24 13:10 UTC, merged

2020-07-02 12:30 UTC, oliviercailloux commented
Pour info : https://github.com/eclipse-ee4j/yasson/issues/423