Creating the main of our program
Sarah-Elhelw/teach_spreadsheets pull request #42
Opened 2020-06-24 12:43 UTC by hedi-guedidi

le programme marche de A à Z finalement sur cette branche.
Remarque : il faut qu'il existe un dossier input avec les fichiers en entrée pour que notre programme fonctionne.

2020-06-24 22:50 UTC, oliviercailloux requested changes

2020-06-24 22:50 UTC, oliviercailloux commented on pom.xml
> +		</dependency>
Cette dépendance est largement redondante avec Guava et la JDK. Je suggère de s’en passer, à moins qu’elle vous rende un service que vous ne trouvez pas dans ces sources et que vous ne pouvez pas remplacer par quelques instructions simples (mais ça m’étonnerait).

2020-06-24 22:50 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/gui/Controller.java
>  			public void handleEvent(Event event) {
Veuillez plutôt appeler une méthode depuis cette méthode, pour réduire le niveau d’imbrication.

2020-06-24 22:50 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/gui/Controller.java
> +						FileUtils.cleanDirectory(new File("output//teacher_assignments"));
Évitez SVP d’utiliser File, cf. cours Path. 

Faites des efforts raisonnables pour effacer seulement les fichiers que votre programme a créé et pas d’autres fichiers éventuellement importants que l’utilisateur final aurait placé là par mégarde ; et pour réduire les dégâts au cas où, à cause d’un bug, le programme effacerait dans le mauvais répertoire. Par exemple, effacer seulement les fichiers *.ods pourrait être adéquat.

2020-06-24 22:50 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/gui/Controller.java
> +					if (!Files.exists(Path.of("output//teacher_assignments"))) {
Il serait plus élégant de définir une fois pour toutes le chemin de sortie et travailler à partir de celui-ci. Cf. exercices Path du cours.

2020-06-24 22:50 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/gui/Controller.java
>  	public static void main(String[] args) throws Exception {
La plupart de ces tâches doivent être faites via des méthodes adéquates dans le contrôleur ou ailleurs, pour ce qui concerne l’initialisation et le fonctionnement correct du contrôleur, tels que la mise en place des listeners. Votre `main` devrait pouvoir être défini dans une autre classe, il ne devrait pas accéder à des éléments privés du contrôleur par exemple.

2020-06-25 01:11 UTC, hedi-guedidi commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/gui/Controller.java
>  			public void handleEvent(Event event) {
C'est fait le contenu de la fonction a été "refactor".

2020-06-25 01:14 UTC, hedi-guedidi commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/gui/Controller.java
>  	public static void main(String[] args) throws Exception {
il y a eu création d'un main dans un package main (class App) pour séparer le plus possible le main du reste des composants.

2020-06-25 21:10 UTC, oliviercailloux requested changes

2020-06-25 21:10 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/gui/Controller.java
> +			LOGGER.error("An error has occured during the writing of the assignment Files.", e);
Ceci est dangereux : si l’écriture ne se produit pas, l’utilisateur final n’en est pas averti, il perdra son travail en fermant le programme et ne comprendra pas ce qui s’est passé (les utilisateurs finaux ne s’amusant pas à regarder les logs en général). 

Voudriez-vous voir ce qui se passe si vous lancez une runtime exception ?

2020-06-25 21:10 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/gui/Controller.java
> +					assignmentToTeacherDocument.save(AssignmentPerTeacherFolderPath.toString() + "//"
Utilisez resolve comme plus haut pour construire le chemin plus élégamment.

2020-06-25 21:10 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/gui/Controller.java
> +		Path AssignmentPerTeacherFolderPath = outputFolderPath.resolve(Path.of("teacher_assignments"));
Conventions de nommage SVP.

2020-06-25 21:10 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/gui/Controller.java
> +				createAssignmentsAndWriteToDisk(courses, CoursePrefs, outputFolderPath);
Je suppose que outputFolderPath ne change jamais. Si ma supposition est correcte, il serait plus simple d’en faire un champ final du Controller initialisé à la construction, j’imagine.

2020-06-25 21:10 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/gui/Controller.java
> +		Files.walkFileTree(folderPath, new SimpleFileVisitor<Path>() {
Je pense (à vérifier SVP) que ceci parcourt récursivement, et donc efface tous les ods trouvés dans n’importe quel sous-répertoire du répertoire de base. C’est très dangereux. Si un bug conduit à partir du répertoire home de l’utilisateur par exemple, votre utilisateur vous maudira pour la fin des temps. Veuillez effacer seulement les ods dans le répertoire lui-même. (Une variante de l’approche que vous avez adopté devrait le permettre.)

2020-06-26 05:52 UTC, hedi-guedidi commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/gui/Controller.java
> +				createAssignmentsAndWriteToDisk(courses, CoursePrefs, outputFolderPath);
Ce outputFolderPath  est en paramètre de la fonction initializeAndLaunchGui qui peut être appelée en dehors du controller afin que l'utilisateur de cette classe passe son propre outputFolderPath  (plus de généralité).

2020-06-26 06:16 UTC, hedi-guedidi commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/gui/Controller.java
> +		Files.walkFileTree(folderPath, new SimpleFileVisitor<Path>() {
En changeant la syntaxe du walkFileTree, cette fonction n'explore que le premier niveau du dossier (tests faits).

2020-06-26 06:18 UTC, hedi-guedidi commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/gui/Controller.java
> +			LOGGER.error("An error has occured during the writing of the assignment Files.", e);
Ajout d'un throw runtime exception juste après.

2020-06-26 15:22 UTC, oliviercailloux requested changes
Il aurait mieux vallu vérifier le contrat plutôt que tester (concernant FileWalk), mais je suis d’accord avec cet usage.

2020-06-26 15:22 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/gui/Controller.java
> +				Files.createDirectory(outputFolderPath);
Utiliser plutôt Files.createDirectories

2020-06-26 15:22 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/gui/Controller.java
> +			throw new RuntimeException();
Utiliser une exception appropriée, pas RE (trop général). Indiquer un message clair.
Ne pas logger et lancer, sauf raison particulière.
Testez et indiquez ici SVP ce qui se produit en cas d’exception dans ce listener.

2020-06-26 15:22 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/gui/Controller.java
> +		List<String[]> stringsToShowAllPreferences = controller
FUTURE. Évitez ces tableaux de Strings de trop bas niveau.

2020-06-26 15:22 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/main/App.java
> +		Files.writeString(Path.of(outputFolderPath.toString() + "//" + "courses.json"), coursesJson);
Utilisez resolve SVP, comme ailleurs.

2020-06-26 16:21 UTC, hedi-guedidi commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/gui/Controller.java
> +		List<String[]> stringsToShowAllPreferences = controller
Issue créé. L'amélioration du code du Controller n'est pas un objectif de cette PR.

2020-06-26 17:04 UTC, hedi-guedidi commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/gui/Controller.java
> +			throw new RuntimeException();
c'est la fonction assignmentToTeacherDocument.save qui lance l'exception  : la seule manière de tester est de mettre un throw dans le code, résultat : 
![image](https://user-images.githubusercontent.com/61390793/85880347-28000700-b7dc-11ea-85c3-97f30605b0c8.png)
L'exception la plus adaptée est ioexception mais ce dernier n'est pas un RE (il faut un RE car on @Override la fonction public void handleEvent(Event event) qui n'envoie pas d'exception).
Solution proposée : création de SummarizerException extends RuntimeException (cf. code).

2020-06-27 22:37 UTC, oliviercailloux approved these changes
Changez SVP l’exception en UncheckedIOException. 

FUTURE : avertir l’utilisateur gentilment via une barre de statut.

2020-06-28 09:28 UTC, merged