ODS read classes and assignment classes
Sarah-Elhelw/teach_spreadsheets pull request #5
Opened 2020-04-15 18:51 UTC by hedi-guedidi

Our group worked on the packages :
-io.github.oliviercailloux.teach_spreadsheets.read
-io.github.oliviercailloux.teach_spreadsheets.assignment
We made test units for each class in these packages.

2020-04-15 19:07 UTC, oliviercailloux requested changes
Veuillez je vous prie d’abord résoudre les conflits, et éviter une PR qui a 38 fichiers modifiés, sans rapports pour la plupart avec votre travail.

2020-04-15 20:12 UTC, hedi-guedidi commented
Les conflits sont résolus.Pour les fichiers modifiés ça correspond à nos classes et aux fichiers du groupe de mike et Inès qu'on a mis à jour manuellement sur notre branche (parce que on a travaillé en parallèle avant leur merge).

2020-04-17 19:52 UTC, oliviercailloux requested changes
Voir SVP doc Instructions projet dans cours pour abréviations.

2020-04-17 19:52 UTC, oliviercailloux commented on .gitignore
> +Docs/Diagrams/Model_fr_FR.properties
Ignorer ce fichier ne fait que masquer le problème, sauf erreur de ma part. (Cf. Papyrus / Various.)

2020-04-17 19:52 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/assignment/Assignment.java
> +	private Set<CourseAssignment> listOfCourseAssignments; // We should not be able to consider more than once a
Veuillez lire BP Style (commentaires) SVP.

2020-04-17 19:52 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/assignment/Assignment.java
> + * This class gathers all the course assignments that were made in a set.
Je ne suis pas sûr de comprendre l’avantage de cette classe par rapport à utiliser simplement un `Set<CourseAssignment>` ?

2020-04-17 19:52 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/assignment/CourseAssignment.java
> +	public static class Builder{
Un Builder pour un Set et un cours, je ne suis pas convaincu de l’intérêt. Envisagez de l’effacer, ou laissez-le, comme vous voulez (OPT). (Par contre votre méthode pour vérifier la cohérence est utile, à conserver.)

2020-04-17 19:52 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/assignment/CourseAssignment.java
> +	private Set<TeacherAssignment> listOfTeacherAssignments; // We should not be able to assign more than once a teacher's assignment to a course.
Évitez SVP d’appeler `list…` un `Set`. `assignments` me semble adéquat et simple.

2020-04-17 19:52 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/assignment/CourseAssignment.java
> +			int sumAssignedGroupsTD=0;
Voyez BP Style formatting SVP.

2020-04-17 19:52 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/assignment/CourseAssignment.java
> +			Objects.requireNonNull(courseAssignmentToBuild.course, "The Course must be set first.");
Plutôt `checkNotNull` (OPT).

2020-04-17 19:52 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/assignment/CourseAssignment.java
> +public class CourseAssignment {
Faites une static factory method qui accepte ces deux paramètres. Faites de `CourseAssignment` un objet immuable, en faisant de votre assignments un `ImmutableSet` (et de `Course` un immuable également).

2020-04-17 19:52 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/assignment/TeacherAssignment.java
> +public class TeacherAssignment {
Indiquer `Immutable` dans la javadoc SVP (après avoir vérifié que Teacher l’est également).

2020-04-17 19:52 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/read/CalcDataInitializer.java
> + * similar to "AA - Saisie des voeux 2016-2017.ods".
Il serait sympathique pour votre lecteur de fournir un lien vers un fichier exemple ou à défaut, au moins, d’indiquer où le trouver (idéalement, dans vos ressources !).

2020-04-17 19:52 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/read/CalcDataInitializer.java
> +	public static CalcDataInitializer newInstance() {
Créer une instance, si tout ce qu’on peut faire dessus est appeler `readDocument`, ne me semble pas utile. Faites plutôt une méthode statique `getData(Path)`. D’ailleurs, il serait plus simple de la mettre dans `CalcData` (mais garder cette classe `initializer` et la placer en visibilité package, appelée en interne par `getData`).

2020-04-17 19:52 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/read/PrefsInitializer.java
> +	public static PrefsInitializer newInstance() {
Même remarque, cette structure me semble inutilement lourde. (OPT)

2020-04-17 19:52 UTC, oliviercailloux commented on src/test/java/io/github/oliviercailloux/teach_spreadsheets/assignment/AssignmentTests.java
> +	void testAddCourseAssignmentWithNullCourseAssignment() {
Ne me semble pas valoir la peine : on ne va pas tester ainsi toutes les méthodes et tous les paramètres…

2020-04-17 19:52 UTC, oliviercailloux commented on src/test/java/io/github/oliviercailloux/teach_spreadsheets/assignment/CourseAssignmentTests.java
> +		});
SVP lisez comment utiliser des méthodes lambda en Java (OPT).

2020-04-17 19:52 UTC, oliviercailloux commented on src/test/java/io/github/oliviercailloux/teach_spreadsheets/read/CalcDataInitializerTests.java
> +				"src\\test\\resources\\io.github.oliviercailloux.teach_spreadsheets.read\\Saisie_des_voeux_format simple.ods");
SVP voir BP Resources.

2020-04-18 19:32 UTC, hedi-guedidi commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/read/CalcDataInitializer.java
> +	public static CalcDataInitializer newInstance() {
`CalcData` et `CalcDataInitializer` ne sont pas dans le même package.Est ce que on peut faire ces modifications en gardant une visibilité publique pour` CalcDataInitializer `?

2020-04-18 21:45 UTC, Sarah-Elhelw commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/assignment/Assignment.java
> + * This class gathers all the course assignments that were made in a set.
Comme nous n'avons pas encore réfléchi à la manière d'affecter des professeurs aux cours, cette classe semble en effet pour l'instant sans intérêt. On se demande s'il ne serait pas préférable de la garder en prévention d'un besoin futur? Nous la supprimerons bien sûr si on constate qu'elle n'a pas d'intérêt.

2020-04-18 21:54 UTC, Sarah-Elhelw commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/assignment/CourseAssignment.java
> +	public static class Builder{
Conceptuellement, je suis plus à l'aise en passant par un Builder : je veux garder l’idée qu’on construit d’abord un objet puis avant de le créer, on s’assure de sa cohérence (dans le build()). Notamment, pour listOfTeacherAssignments, l'idée serait de construire la liste (avec addTeacherAssignment() dans le Builder pour, à terme, renvoyer une liste immuable pour instancier l'attribut en question.

2020-04-18 22:10 UTC, Sarah-Elhelw commented on src/test/java/io/github/oliviercailloux/teach_spreadsheets/assignment/AssignmentTests.java
> +	void testAddCourseAssignmentWithNullCourseAssignment() {
Les méthodes pour la classe Assignment n'étant pas encore définies, cette classe n'a donc pour l'instant pas de méthodes intéressantes à tester. Est-il donc possible de ne pas systématiquement associer de test unitaire à une classe qu'on vous soumet ?

2020-04-19 14:29 UTC, hedi-guedidi commented on .gitignore
> +Docs/Diagrams/Model_fr_FR.properties
On a supprimer ces deux ligne.Dans Papyrus / Various vous estimez que le problème vient de l'élément label.Sauf erreur de ma part, on n'utilise plus cette element (mais il se peut qu'on la fait à un moment ). On aimerait bien garder ces deux lignes pour être sur de ne pas inclure ces fichiers dans tous les cas dans le dépôt github.

2020-04-19 15:18 UTC, hedi-guedidi commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/read/PrefsInitializer.java
> +	public static PrefsInitializer newInstance() {
Pour le moment on ne voit pas de meilleure structure pour stocker les noms des tables.

2020-04-19 15:31 UTC, hedi-guedidi commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/read/CalcDataInitializer.java
> +	public static CalcDataInitializer newInstance() {
fait

2020-04-20 10:46 UTC, oliviercailloux commented on .gitignore
> +Docs/Diagrams/Model_fr_FR.properties
Votre raisonnement a du sens, mais je ne suis pas convaincu. Si jamais vous utilisez (ou d’autres contributeurs utilisent) par mégarde à l’avenir des mécanismes qui mènent Papyrus à stocker des informations dans ce fichier, je ne verrai pas la même chose que vous. C’est un moindre mal que ce fichier soit stocké sur le serveur s’il est effectivement utilisé pour stocker des infos. Et mieux vaut que vous soyez avertis par git si le fichier réapparait, cela nous donne une chance de voir et corriger le problème.

2020-04-20 10:50 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/assignment/Assignment.java
> + * This class gathers all the course assignments that were made in a set.
Là encore, votre raisonnement ne manque pas de sens, mais j’adopterais plutôt la perspective inverse. Faisons au plus simple, jusqu’à ce qu’une complexité supplémentaire soit justifiée. Cette classe restera de toute façon dans votre historique, prête à être récupérée lorsque (et si) son besoin devient clair.

2020-04-20 11:34 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/assignment/CourseAssignment.java
> +	private CourseAssignment(Course course, ImmutableSet<TeacherAssignment> finalTeacherAssignments) {
Voyez SVP BP Local design#accept general parameters

2020-04-20 11:34 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/assignment/CourseAssignment.java
> +		this.course = Preconditions.checkNotNull(course, "The course must not be null.");
Incorrect, teacherAssignments n’est pas affecté. En outre, je ne vois pas pourquoi ce constructeur serait utile : ne veut-on pas toujours au moins un teacher assignment ?

2020-04-20 11:34 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/assignment/CourseAssignment.java
> +	public static CourseAssignment newInstance(Course course, ImmutableSet<TeacherAssignment> finalTeacherAssignments) {
Ceci passe outre les vérifications du builder et permet de créer un course assignment qui n’offre pas les garanties voulues.

2020-04-20 11:34 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/read/CalcDataInitializer.java
> + * similar to <a href="../../../../../../../../src/test/resources/io/github/oliviercailloux/teach_spreadsheets/read/AA - Saisie des voeux 2016-2017_Emplois-du-temps.ods">"AA - Saisie des voeux 2016-2
J’aurais plutôt choisi un lien vers GitHub (OPT).

2020-04-20 11:34 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/read/CalcDataInitializer.java
> +	public static CalcDataInitializer newInstance() {
Je ne vois pas d’avantage à garder `CDInitializer` publique. Pourquoi ne pas la changer de package ? Elle est étroitement liée à CalcData, de toute façon.

2020-04-20 11:36 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/read/PrefsInitializer.java
> +	public static PrefsInitializer newInstance() {
Mon commentaire était sur `PrefsInitilaizer#newInstance`. Mettez SVP en FUTURE : réfléchir aux structures d’initialisations et builders. (Cf. instructions projet)

2020-04-20 11:38 UTC, oliviercailloux commented on src/test/java/io/github/oliviercailloux/teach_spreadsheets/assignment/AssignmentTests.java
> +	void testAddCourseAssignmentWithNullCourseAssignment() {
Mieux vaut pas de test qu’un test inutile (et il ne faut pas tester des choses triviales, qui ne peuvent pas échouer tellement le code est simple). Mieux vaut un test utile que pas de test. Si une classe est tellement simple qu’elle n’offre rien à tester, car tout y est trivial, alors, pas de test est la bonne solution.

2020-04-20 11:40 UTC, oliviercailloux requested changes

2020-04-20 11:40 UTC, oliviercailloux commented on src/test/java/io/github/oliviercailloux/teach_spreadsheets/read/CalcDataInitializerTests.java
> +				"src\\test\\resources\\io\\github\\oliviercailloux\\teach_spreadsheets\\read\\Saisie_des_voeux_format simple.ods");
Lecture depuis class path à améliorer, cf. BP Resources (FUTURE).

2020-04-20 19:09 UTC, hedi-guedidi commented on .gitignore
> +Docs/Diagrams/Model_fr_FR.properties
D'accord. On a supprimé les deux dernières lignes.

2020-04-20 20:47 UTC, hedi-guedidi commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/read/PrefsInitializer.java
> +	public static PrefsInitializer newInstance() {
Est-ce qu'on peut plutôt rendre la méthode principale de cette classe statique et supprimer la factory ?

2020-04-29 08:12 UTC, Sarah-Elhelw commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/assignment/CourseAssignment.java
> +		this.course = Preconditions.checkNotNull(course, "The course must not be null.");
teacherAssignment est un attribut d’un CourseAssignment.Builder. Il est initialisé à un LinkedHashSet vide dès qu’on instancie un CourseAssignment.Builder (l.59). On avait imaginé son rôle comme ceci : teacherAssignment est un objet intermédiaire permettant la construction de finalTeacherAssignment qui est immuable.
Enfin, dans le build(), nous avons ajouté une ligne de vérification qui s’assure, avant de construire un CourseAssignment , qu’il contient au moins un teacherAssignment.

2020-05-01 17:57 UTC, merged