Writing ODS Summarizer
Sarah-Elhelw/teach_spreadsheets pull request #6
Opened 2020-04-19 19:51 UTC by Semida-Buzdugan

Creation of a new Class which creates an ODS, adds headers to this ODS and the preferences of the teachers for each course.

2020-04-20 15:12 UTC, oliviercailloux requested changes
Veuillez voir SVP BP Style (pour pom.xml, que git voit entièrement changé).
Voir instructions projets pour abréviations.

2020-04-20 15:12 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/CalcWrite/OdsSummarizer.java
> +	public static SpreadsheetDocument createSummarizedOds(ImmutableSet <Course> allCourses, ImmutableSet <CoursePref> prefs) throws Throwable {
Lancer SVP qqch de plus spécifique que Throwable, sinon on ne peut pas distinguer un problème lié à l’API de création du document d’un autre problème.

2020-04-20 15:12 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/CalcWrite/OdsSummarizer.java
> +		SpreadsheetDocument document =createAnEmptyOds();
Voyez BP Style Formatting SVP.

2020-04-20 15:12 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/CalcWrite/OdsSummarizer.java
> +		boolean test=false; // this test helps us to see when there is no teachers for a course
Noms de variables descriptives SVP. `courseHasTeacher`, par exemple. À initialiser dans la boucle for.

2020-04-20 15:12 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/CalcWrite/OdsSummarizer.java
> +			if (test==false) {
`if (!courseHasTeacher)`

2020-04-20 15:12 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/CalcWrite/OdsSummarizer.java
> +		document.save("target//FichierAgrege.ods");
Cette méthode fait croire qu’elle retourne le document créé (pour que l’utilisateur en fasse ce qu’il veut), ce qui est le comportement général et correct attendu. Pas qu’elle l’écrit sur le disque à un endroit non configurable. À retirer SVP.

2020-04-20 15:12 UTC, oliviercailloux commented on src/test/java/io/github/oliviercailloux/teach_spreadsheets/CalcWrite/testOdsSummarizer.java
> +public class testOdsSummarizer {
Lire SVP BP Style Writing code.

2020-04-20 15:12 UTC, oliviercailloux commented on src/test/java/io/github/oliviercailloux/teach_spreadsheets/CalcWrite/testOdsSummarizer.java
> +	void testFichierAgrege() throws Throwable{
In English, please. Agrege n’existe ni en anglais, ni en français.

2020-04-20 15:12 UTC, oliviercailloux commented on src/test/java/io/github/oliviercailloux/teach_spreadsheets/CalcWrite/testOdsSummarizer.java
> +				assertEquals( expectedvalue6, actualvalue6);
La longueur de ce code le rend plus difficile à lire que nécessaire. Envisagez de résumer ces 24 lignes en 6 lignes en évitant les variables intermédiaires. (OPT)

2020-04-20 15:12 UTC, oliviercailloux commented on src/test/java/io/github/oliviercailloux/teach_spreadsheets/CalcWrite/testOdsSummarizer.java
> +		Files.delete(infile);
BP Resources (FUTURE)

2020-04-20 15:12 UTC, oliviercailloux commented on src/test/java/io/github/oliviercailloux/teach_spreadsheets/CalcWrite/testOdsSummarizer.java
> +	void testFichierAgrege() throws Throwable{
Test très utile en effet ; mais il serait encore plus pertinent de comparer le fichier écrit à un fichier se trouvant dans votre class path, pour qu’on puisse voir facilement un exemple de ce qui est produit. (FUTURE)

2020-04-20 23:41 UTC, oliviercailloux requested changes
Voyez SVP les problèmes suivants relevés précédemment, qui sauf erreur de ma part sont toujours présents.
- Problème POM toujours présent.
- Lancer `Exception` pose le même genre de problème que `Throwable`.
- FUTURE d’un commentaire précédent ne semble pas avoir été pris en compte.

2020-04-20 23:41 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/CalcWrite/OdsSummarizer.java
> +			boolean courseHasTeacher = false; // this test helps us to see when there if they are teachers who want to
Voyez SVP BP Style comments.

2020-05-04 09:56 UTC, hedi-guedidi commented
Va être remplacer par une nouvelle PR.

2020-05-04 09:57 UTC, closed without merging