It2 hedi
Sarah-Elhelw/teach_spreadsheets pull request #8
Opened 2020-04-28 13:17 UTC by hedi-guedidi

Ce PR fait suite au fait suite à la PR #5 pour les classes du package read.Les commentaires concernés : https://github.com/Sarah-Elhelw/teach_spreadsheets/pull/5#discussion_r410435818 , https://github.com/Sarah-Elhelw/teach_spreadsheets/pull/5#discussion_r411305113 et https://github.com/Sarah-Elhelw/teach_spreadsheets/pull/5#discussion_r411308553.

2020-04-30 08:09 UTC, oliviercailloux requested changes
Donnez je vous prie un nom à votre tâche descriptif de son objectif (et pas : It2 hedi), qu’on s’y retrouve.

2020-04-30 08:09 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/read/CourseAndPrefReader.java
> +	LinkedHashSet<Course> courseList;
Voyez SVP BP Local design return types and fields

2020-04-30 08:09 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/read/CourseAndPrefReader.java
> +			setInfoPref(sheet, prefBuilder, currentCol + 8, currentRow); // Beware, there are hidden columns in the ods
Voici un commentaire effectivement très utile pour le lecteur. Mais voyez SVP BP Style.

2020-04-30 08:09 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/read/CourseAndPrefReader.java
> +
Évitez SVP les lignes blanches inutiles (OPT).

2020-04-30 08:09 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/read/CourseAndPrefReader.java
> +
Ligne blanche inutile, on peut se demander brièvement si le commentaire en question est bien à associer à cette méthode ou si c’est juste un commentaire qui aurait dû se trouver ailleurs et qui s’est perdu. (OPT)

2020-04-30 08:09 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/read/ReaderLib.java
> +		return false;
Évitez cette duplication de code SVP en factorisant le code commun aux deux méthodes. (BP local design factor)

2020-04-30 08:09 UTC, oliviercailloux commented on src/test/java/io/github/oliviercailloux/teach_spreadsheets/read/CalcDataInitializerTests.java
> +			assertEquals(expectedTeacher, actualTeacher.toString());
Peu lisible. Vérifiez un par un SVP que chaque information (nom, prénom, etc.) est correcte. Même chose ci-dessous.

2020-04-30 08:09 UTC, oliviercailloux commented on src/test/java/io/github/oliviercailloux/teach_spreadsheets/read/CourseAndPrefReaderTests.java
> +	// Creating a fake teacher :
BP Style

2020-04-30 14:55 UTC, hedi-guedidi commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/read/ReaderLib.java
> +		return false;
fait.

2020-05-01 17:44 UTC, oliviercailloux approved these changes
Fusion ok moyennant corrections mineures indiquées.

2020-05-01 17:44 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/read/CourseAndPrefReader.java
> +	Set<Course> courseList;
Évitez SVP d’appeler …list un `Set`. Le nom `courses` est simple et conviendrait ici.

2020-05-01 17:44 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/read/CourseAndPrefReader.java
> +		LinkedHashSet<CoursePref> coursePrefList = new LinkedHashSet<>();
Utiliser un ImmutableSet Builder serait plus clair. Nom de variable, même chose que ci-dessus. Généralité du type, même chose que précédemment. (OPT)

2020-05-01 17:57 UTC, merged