Json reading and writing classes
Sarah-Elhelw/teach_spreadsheets pull request #9
Opened 2020-05-02 09:30 UTC by Sarah-Elhelw

Notre groupe a travaillé sur la tâche suivante : implémentation des classes JsonRead et JsonWrite du package io.github.oliviercailloux.teach_spreadsheets.json et de leurs tests unitaires.

2020-05-02 15:36 UTC, oliviercailloux requested changes
Je vous ai indiqué des commentaires pour améliorer ces fonctions si la décision est prise de poursuivre dans cette voie, mais je ne suis pas entièrement convaincu par cette approche à ce stade. Je vous invite plutôt à adopter le code de plaquette-mido qui lit du XML (et non du Json), qui est nettement plus robuste aux changements éventuels de formats, pour lire depuis RefRof.
(Le reste, qui ne vient pas de RefRof, n’est pas en cause.)

Vous pouvez décider de mettre ceci en FUTURE et terminer néanmoins cette PR selon la voie que vous avez choisie pour le moment, même pour ce qui vient de RefRof, pour ne pas bloquer le projet à court terme, mais en prenant le risque de perdre du temps puisque cet aspect devra être modifié par la suite.

2020-05-02 15:36 UTC, oliviercailloux commented on pom.xml
> +			<artifactId>javax.json-api</artifactId>
J’imagine que `javax.json-api` et `jakarta.json-api` sont deux versions de la même bibliothèque (la deuxième étant plus récente), auquel cas, les inclure toutes les deux est sûrement une très mauvaise idée.

2020-05-02 15:36 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/json/JsonRead.java
> +	private static String formatToArray(String textArray) {
Je vous prie d’utiliser les API Json appropriées pour éviter de devoir décomposer vous-même le contenu des chaines contenant du Json, problème que les bibliothèques dédiées existantes sont faites pour résoudre. Vous devriez pouvoir demander à Json B de désérialiser un vecteur dans une liste, par exemple. Indiquez-moi si des subtilités m’ont échappées.

2020-05-02 15:36 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/json/JsonRead.java
> +		checkNotNull(resourceUrl, "The resource does not exist.");
Lisez BP Exceptions SVP.

2020-05-02 15:36 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/json/JsonRead.java
> +	private static String readFile(String fileName) throws IOException, URISyntaxException {
C’est un nom de ressource que vous attendez ici, pas de fichier. Cette méthode est peu claire, car elle ne fonctionnera que pour les arguments qui correspondent à des ressources, qui sont censées être peu nombreuses et connues à l’avance. Je doute de son utilité.

2020-05-02 15:36 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/json/JsonRead.java
> +	public static ImmutableSet<Course> getSetOfCoursesInfo(String fileName) throws Exception {
En l’état, cette méthode ne fonctionne que pour des ressources du class path, ce qui est inutilement restrictif. Prenez plutôt un `String` en paramètre, contenant directement le contenu json à partir duquel construire les cours. (Rien n’empêche de créer une méthode supplémentaire qui lit depuis le class path si cela vous est utile par ailleurs.)

2020-05-02 15:36 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/json/JsonRead.java
> +		});
Il ne convient pas de relire le fichier login et rétablir l’authentification par défaut chaque fois qu’on veut lire une page de RefRof : cela duplique le travail inutilement.

2020-05-02 15:36 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/json/JsonRead.java
> +			return in.readLine();
Je ne comprends pas l’objectif de ce code. Pourquoi lire seulement la première ligne ? Si c’est ce que vous voulez faire, il faut le documenter et l’annoncer dans le nom de la méthode. En l’état, on s’attend à ce que toute la page à l’adresse fournie soit lue.

Par ailleurs, il convient sans-doute d’utiliser plutôt JAX-RS client (cf. page du cours correspondante).

2020-05-02 15:36 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/json/JsonRead.java
> +		return formatToArray(finalText);
Si je suis bien, ce code lit le json en entrée, extrait toutes les informations utiles pour construire un enseignant, les remet dans un nouveau json, pour qu’on puisse ensuite passer ce nouveau json à JSON-B afin qu’il construise un enseignant ? Si c’est bien cela, je ne parviens pas à voir un avantage de ceci par rapport à simplement renvoyer un enseignant construit à partir des données lues par cette méthode ?

2020-05-02 15:36 UTC, oliviercailloux commented on src/test/java/io/github/oliviercailloux/teach_spreadsheets/json/JsonReadTests.java
> +		String expectedIS = "[Course{name=PRE-RENTREE : Mathématiques, countGroupsTD=0, countGroupsCMTD=6, countGroupsTP=0, countGroupsCMTP=0, countGroupsCM=0, nbMinutesTD=0, nbMinutesCMTD=900, nbMinutesTP
FORMAT SVP

2020-05-02 15:36 UTC, oliviercailloux commented on src/test/java/io/github/oliviercailloux/teach_spreadsheets/json/JsonReadTests.java
> +		assertEquals(expectedIS, actualIs);
Ce test serait nettement plus lisible s’il comparait les cours obtenus et attendus morceau par morceau, plutôt que tout convertir en un énorme string.

2020-05-02 15:36 UTC, oliviercailloux commented on src/test/java/io/github/oliviercailloux/teach_spreadsheets/json/JsonWriteTests.java
> +				Path jsonPath = inMemoryFs.getPath("courses.json");
Bel usage de Jimfs. Mais en l’occurrence, il me semble inutilement sophistiqué : prévoyez plutôt une méthode qui écrit dans un string plutôt que dans un path, ce sera nettement plus simple à relire et votre test en sera nettement simplifié. Voir BP Ressources si nécessaire.

2020-05-02 16:57 UTC, Sarah-Elhelw commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/json/JsonRead.java
> +	private static String formatToArray(String textArray) {
Pour désérialiser une liste json en utilisant jsonb, il me faut fournir uniquement la liste commençant par ‘[‘ et terminant par ‘]’. Si je rentrer une chaîne contenant du json où la liste est valeur d’une clé K, le désérialiser de jsonb ne le comprendrait pas. Il me fallait donc une fonction qui extrait uniquement la liste du json. J’ai finalement remplacé le rôle de cette fonction : elle ne décompose plus le contenu de la chaîne mais vérifie seulement le format de la chaîne.

2020-05-02 18:36 UTC, Sarah-Elhelw commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/json/JsonRead.java
> +			return in.readLine();
Il n’y a qu’une seule ligne dans la page RefRof lue. C’est pour cela que je ne lis qu’une seule ligne. J’ai ajouté cette nouvelle précision dans la doc.

2020-05-02 18:56 UTC, Sarah-Elhelw commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/json/JsonRead.java
> +			return in.readLine();
Il n’y a qu’une seule ligne dans la page RefRof lue. C’est pour cela que je ne lisais qu’une seule ligne. J’ai ajouté cette nouvelle précision dans la doc.

2020-05-03 07:34 UTC, Sarah-Elhelw commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/json/JsonRead.java
> +		return formatToArray(finalText);
J’avais aussi cette impression en codant la fonction. Toutefois, je trouvais le json sur RefRof difficile à lire (avec beaucoup d’informations imbriquées), c’est pourquoi j’ai voulu construire un json simplifié pour une éventuelle réutilisation ultérieure (par exemple, écrire un fichier json des professeurs comme on a pu le faire pour les cours dans la classe JsonWrite).

2020-05-03 07:50 UTC, Sarah-Elhelw commented on src/test/java/io/github/oliviercailloux/teach_spreadsheets/json/JsonReadTests.java
> +		String expectedIS = "[Course{name=PRE-RENTREE : Mathématiques, countGroupsTD=0, countGroupsCMTD=6, countGroupsTP=0, countGroupsCMTP=0, countGroupsCM=0, nbMinutesTD=0, nbMinutesCMTD=900, nbMinutesTP
J'ai appliqué le formatage automatique d'Eclipse au niveau de la ligne 16 mais je n'ai pas eu de modification.

2020-05-03 09:07 UTC, Sarah-Elhelw commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/json/JsonRead.java
> +		checkNotNull(resourceUrl, "The resource does not exist.");
Je n'ai pas compris ce commentaire. Il me faut vérifier que resourceUrl n'est pas null pour éviter un NullPointerException à la ligne 71.

2020-05-04 14:37 UTC, oliviercailloux commented on src/test/java/io/github/oliviercailloux/teach_spreadsheets/json/JsonReadTests.java
> +		String expectedIS = "[Course{name=PRE-RENTREE : Mathématiques, countGroupsTD=0, countGroupsCMTD=6, countGroupsTP=0, countGroupsCMTP=0, countGroupsCM=0, nbMinutesTD=0, nbMinutesCMTD=900, nbMinutesTP
Vous avez raison, autant pour moi. La longueur de cette ligne était due à cette chaine très longue, qu’Eclipse ne fractionne pas automatiquement.

2020-05-04 15:11 UTC, oliviercailloux requested changes
J’en profite pour remarquer que le `studyYear` dans `Course` devrait être un `int`, et documenté comme étant l’année de début d’année académique (par exemple on prend 2019 pour l’année académique 2019 à 2020). FUTURE

Je propose de ne pas fusionner cette PR pour l’instant, laissons-la de côté en attendant de voir ce qu’on peut vraiment tirer de ROF en XML et on intégrera ensuite la partie Json nécessaire pour les infos manquantes.

2020-05-04 15:11 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/json/JsonRead.java
> +	private static void checkFormatOfArray(String textArray) {
Cette méthode a peu d’intérêt : s’il y a un problème de format, la bibliothèque Json le remarquera pour vous, et de toute façon la méthode ne teste qu’une partie de ce qu’il faut vérifier pour s’assurer de l’exactitude du format. Mieux vaut laisser tomber cette ambition, je pense, et laisser faire la bibliothèque sous-jacente, qui le fera très bien à votre place. OPT

2020-05-04 15:11 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/json/JsonRead.java
> +	public static ImmutableSet<Course> getSetOfCoursesInfo(String textFile) throws Exception {
`textFile` n’est pas (ou plus) le nom qui convient ici.

2020-05-04 15:11 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/json/JsonRead.java
> +	public static ImmutableSet<Course> getSetOfCoursesInfo(String textFile) throws Exception {
Veuillez ne pas envoyer une `Exception`, c’est très polluant (il faudra la trimballer partout où cette méthode est appelée). Je sais que ce n’est pas votre faute mais la faute de `Jsonb` (c’est une erreur de conception malencontreuse de cette bibliothèque). Vous pouvez attraper cette exception et l’enrober d’une `IllegalArgumentException` par exemple (ce qui est correct si on fait l’hypothèse que la conversion échoue si, et seulement si, le texte reçu n’est pas du json correct, ce qui parait plausible).

2020-05-04 15:11 UTC, oliviercailloux commented on src/test/java/io/github/oliviercailloux/teach_spreadsheets/json/JsonReadTests.java
> +		URL resourceUrl = JsonRead.class.getResource("Courses.json");
Ce fichier n’est pas dans votre dépôt sur GitHub.

2020-05-04 15:11 UTC, oliviercailloux commented on src/test/java/io/github/oliviercailloux/teach_spreadsheets/json/JsonReadTests.java
> +		URL resourceUrl = JsonRead.class.getResource("LoginRefRof.json");
Ce fichier ne doit pas venir de votre class path, puisque l’utilisateur final est censé le modifier.

2020-05-04 15:11 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/json/JsonWrite.java
> +		checkNotNull(serialized);
Voyez SVP BP Exceptions

2020-05-04 15:27 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/json/JsonRead.java
> +			return in.readLine();
Ce n’est pas une excuse. Conceptuellement, ce code doit tout lire, pas juste la première ligne. Si la page change et le retour s’étale sur plusieurs lignes, ce code échouera, sans raison apparente.

2020-05-04 15:28 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/json/JsonRead.java
> +		return formatToArray(finalText);
Les commentaires sont maintenant partiellement incorrects, ce qui illustre bien mon conseil général d’éviter les commentaires inutiles, car ils sont difficiles à maintenir corrects (et des commentaires incorrects sont bien pires que pas de commentaires). Je suggère leur effacement.

2020-05-04 15:41 UTC, Sarah-Elhelw commented on src/test/java/io/github/oliviercailloux/teach_spreadsheets/json/JsonReadTests.java
> +		URL resourceUrl = JsonRead.class.getResource("Courses.json");
Je ne comprends pas, je le retrouve bien de mon côté : 
![image](https://user-images.githubusercontent.com/45911833/80984676-732a1900-8e2e-11ea-8358-bb113f2e4d26.png)

2020-05-04 15:43 UTC, Sarah-Elhelw commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/json/JsonRead.java
> +	public static ImmutableSet<Course> getSetOfCoursesInfo(String textFile) throws Exception {
Par textFile, je voulais simplement dire "texte du fichier".

2020-05-04 22:14 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/teach_spreadsheets/json/JsonRead.java
> +	private static String formatToArray(String textArray) {
Ok, intéressant. Laissez cette méthode telle qu’elle est, elle est justifiée si cela permet d’éviter une liste vide envoyée par erreur. Ajoutez SVP un test unitaire qui illustre ce comportement bizarre de Json-B (quand il renvoie une liste vide alors qu’il ne devrait pas). je vais investiguer. FUTURE

2020-05-04 22:15 UTC, oliviercailloux commented on src/test/java/io/github/oliviercailloux/teach_spreadsheets/json/JsonReadTests.java
> +		URL resourceUrl = JsonRead.class.getResource("Courses.json");
Vous avez raison, erreur de ma part.

2020-06-07 13:29 UTC, merged